# Generated by Django 5.2.4 on 2025-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audio_length',
            field=models.BigIntegerField(blank=True, help_text='Audio file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='audio_type',
            field=models.CharField(blank=True, help_text='Audio MIME type (e.g., audio/mpeg)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='content_encoded',
            field=models.TextField(blank=True, help_text='HTML encoded content/show notes', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, help_text='Episode description', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.DurationField(blank=True, help_text='Episode duration', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(blank=True, help_text='Episode number', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_type',
            field=models.CharField(blank=True, help_text='Episode type (full, trailer, bonus)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='itunes_episode_type',
            field=models.CharField(blank=True, help_text='iTunes episode type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='itunes_explicit',
            field=models.BooleanField(default=False, help_text='iTunes explicit content flag for episode'),
        ),
        migrations.AddField(
            model_name='episode',
            name='itunes_keywords',
            field=models.CharField(blank=True, help_text='iTunes keywords for episode', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='pub_date',
            field=models.DateTimeField(blank=True, help_text='Publication date from RSS', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='season_number',
            field=models.IntegerField(blank=True, help_text='Season number', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Episode subtitle', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='author',
            field=models.CharField(blank=True, help_text='Podcast author/creator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='copyright',
            field=models.CharField(blank=True, help_text='Copyright information', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='image_url',
            field=models.URLField(blank=True, help_text='Podcast artwork URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='itunes_categories',
            field=models.JSONField(blank=True, help_text='iTunes categories as JSON', null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='itunes_explicit',
            field=models.BooleanField(default=False, help_text='iTunes explicit content flag'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='itunes_image_url',
            field=models.URLField(blank=True, help_text='iTunes specific image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='itunes_keywords',
            field=models.CharField(blank=True, help_text='iTunes keywords', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='itunes_type',
            field=models.CharField(blank=True, help_text='iTunes podcast type (episodic/serial)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='language',
            field=models.CharField(blank=True, help_text="Language code (e.g., 'en')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='last_build_date',
            field=models.DateTimeField(blank=True, help_text='Last build date from RSS', null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Owner email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Owner name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='pub_date',
            field=models.DateTimeField(blank=True, help_text='Last publication date from RSS', null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='subtitle',
            field=models.CharField(blank=True, help_text='iTunes subtitle', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='summary',
            field=models.TextField(blank=True, help_text='iTunes summary (longer description)', null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this RSS feed', related_name='podcasts', to='audio_processing.tag'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.URLField(help_text='RSS feed URL', unique=True),
        ),
    ]
