# Generated by Django 5.2.4 on 2025-08-29 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0002_episode_audio_length_episode_audio_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0, help_text='Number of views for this analytics record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(blank=True, help_text='Episode this analytics record refers to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_analytics', to='audio_processing.episode')),
                ('podcast', models.ForeignKey(blank=True, help_text='Podcast this analytics record refers to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_analytics', to='audio_processing.podcast')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='audio_proce_user_id_305780_idx'), models.Index(fields=['podcast'], name='audio_proce_podcast_3c6023_idx'), models.Index(fields=['episode'], name='audio_proce_episode_026c8c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('podcast__isnull', False), ('episode__isnull', False), _connector='OR'), name='user_analytics_has_entity'), models.CheckConstraint(condition=models.Q(('podcast__isnull', False), ('episode__isnull', False), _negated=True), name='user_analytics_single_entity')],
            },
        ),
    ]
