# Generated by Django 5.2.4 on 2025-09-02 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0003_useranalytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Contact email address for the podcast owner', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(help_text="Owner's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Owner's last name", max_length=100)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current approval status', max_length=20)),
                ('date_approved', models.DateTimeField(blank=True, help_text='Date when the owner was approved', null=True)),
                ('date_rejected', models.DateTimeField(blank=True, help_text='Date when the owner was rejected', null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Internal notes about the approval/rejection decision', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this owner record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this owner record was last updated')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin user who approved/rejected this owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_podcast_owners', to=settings.AUTH_USER_MODEL)),
                ('podcast', models.OneToOneField(help_text='The podcast this owner is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='audio_processing.podcast')),
            ],
            options={
                'verbose_name': 'Podcast Owner',
                'verbose_name_plural': 'Podcast Owners',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approval_status'], name='audio_proce_approva_7d269c_idx'), models.Index(fields=['email'], name='audio_proce_email_b3a512_idx'), models.Index(fields=['created_at'], name='audio_proce_created_23d6a9_idx')],
            },
        ),
    ]
