# Generated by Django 5.2.4 on 2025-09-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0004_podcastowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='has_public_transcript',
            field=models.BooleanField(default=False, help_text='Whether the episode has a public transcript'),
        ),
    ]
