# Generated by Django 5.2.4 on 2025-09-02 20:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0006_remove_episode_itunes_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The actual quote text content', validators=[django.core.validators.MinLengthValidator(10)])),
                ('speaker', models.CharField(blank=True, help_text='Name or identifier of the person who said this quote', max_length=200, null=True)),
                ('timestamp', models.DurationField(blank=True, help_text='Timestamp in the episode where this quote appears (e.g., 00:15:30)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this quote was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this quote was last updated')),
                ('episode', models.ForeignKey(help_text='The episode this quote is from', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='audio_processing.episode')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['episode'], name='audio_proce_episode_e245ec_idx'), models.Index(fields=['speaker'], name='audio_proce_speaker_941a62_idx'), models.Index(fields=['created_at'], name='audio_proce_created_51dedd_idx')],
            },
        ),
    ]
