# Generated by Django 5.2.4 on 2025-09-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_processing", "0009_podcast_slug"),
    ]

    def gen_unique_slug(apps, schema_editor):
        Episode = apps.get_model("audio_processing", "Episode")
        Podcast = apps.get_model("audio_processing", "Podcast")
        from django.utils.text import slugify

        for episode in Episode.objects.filter(
            models.Q(slug__isnull=True) | models.Q(slug="")
        ):
            podcast = episode.podcast
            podcast_slug = getattr(podcast, "slug", None) or "podcast"
            base_slug = f"{podcast_slug}-{slugify(episode.title or str(episode.pk))}"
            slug = base_slug
            counter = 1
            while Episode.objects.filter(slug=slug).exclude(pk=episode.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            episode.slug = slug
            episode.save(update_fields=["slug"])

    operations = [
        migrations.AddField(
            model_name="episode",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique slug for episode, prefixed with podcast slug",
                max_length=512,
            ),
        ),
        migrations.RunPython(gen_unique_slug, reverse_code=migrations.RunPython.noop),
    ]
