# Generated by Django 5.2.4 on 2025-08-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0009_podcast_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
    ]
