# Generated by Django 5.2.4 on 2025-09-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_processing", "0013_alter_entity_name_alter_entity_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="raw_audio_url",
            field=models.URLField(
                help_text="URL of the raw audio file", max_length=2000, unique=True
            ),
        ),
    ]
