# Generated by Django 5.2.4 on 2025-09-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_processing", "0015_alter_episode_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="Episode artwork URL", max_length=1000, null=True
            ),
        ),
    ]
