# Generated by Django 5.2.4 on 2025-09-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "audio_processing",
            "0019_alter_podcast_author_alter_podcast_copyright_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="processing_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when episode processing was completed",
                null=True,
            ),
        ),
    ]
