# Generated by Django 5.2.4 on 2025-10-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_processing", "0024_episode_topics_topic_topic_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
