
services:
  webapp: &web
    image: retyped/backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/data/postgres
    environment:
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_DB=audio_processing

  #worker:
  #  <<: *web
  #  image: retyped/backend:latest
  #  command: celery -A config worker -B -l info --loglevel=info
  #  depends_on:
  #    - db


volumes:
  dbdata:
